# Generated by Django 5.2.4 on 2025-07-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
