# Generated by Django 5.2.4 on 2025-07-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0004_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='Oziq-ovqat',
            new_name='title',
        ),
    ]
